const tools = [
  { slug: 'pdf-to-jpg', title: 'PDF to JPG' },
  { slug: 'jpg-to-pdf', title: 'JPG to PDF' },
  { slug: 'compress-pdf', title: 'Compress PDF' },
  { slug: 'merge-pdf', title: 'Merge PDF' },
  { slug: 'split-pdf', title: 'Split PDF' },
  { slug: 'pdf-to-word', title: 'PDF to Word' },
  { slug: 'word-to-pdf', title: 'Word to PDF' },
  { slug: 'pdf-to-ppt', title: 'PDF to PPT' },
  { slug: 'ppt-to-pdf', title: 'PPT to PDF' },
  { slug: 'pdf-to-excel', title: 'PDF to Excel' },
  { slug: 'image-to-ocr', title: 'Image to Text (OCR)' },
  { slug: 'pdf-ocr', title: 'OCR PDF' },
  { slug: 'text-to-pdf', title: 'Text to PDF' },
  { slug: 'pdf-to-txt', title: 'PDF to Text' },
  { slug: 'translate-ocr', title: 'OCR + Translate' },
  { slug: 'image-compress', title: 'Compress Images' },
  { slug: 'resize-image', title: 'Resize Image' },
  { slug: 'convert-image', title: 'Image Converter' },
  { slug: 'png-to-jpg', title: 'PNG to JPG' },
  { slug: 'remove-bg', title: 'Remove Background' },
  { slug: 'protect-pdf', title: 'Protect PDF' },
  { slug: 'unlock-pdf', title: 'Unlock PDF' },
  { slug: 'rotate-pdf', title: 'Rotate PDF' },
  { slug: 'watermark-pdf', title: 'Watermark PDF' },
  { slug: 'pdf-repair', title: 'Repair PDF' },
  { slug: 'excel-to-pdf', title: 'Excel to PDF' },
  { slug: 'ppt-to-images', title: 'PPT to Images' },
  { slug: 'csv-to-excel', title: 'CSV to Excel' },
  { slug: 'html-to-pdf', title: 'HTML to PDF' },
  { slug: 'split-image', title: 'Split Image' },
  { slug: 'combine-images', title: 'Combine Images' },
  { slug: 'pdf-to-epub', title: 'PDF to EPUB' },
  { slug: 'epub-to-pdf', title: 'EPUB to PDF' },
  { slug: 'pdf-metadata', title: 'Edit PDF Metadata' },
  { slug: 'pdf-sign', title: 'Sign PDF' },
  { slug: 'compress-image-batch', title: 'Batch Image Compressor' },
  { slug: 'ocr-api-demo', title: 'OCR API Demo' },
  { slug: 'compare-pdfs', title: 'Compare PDFs' },
  { slug: 'split-by-size', title: 'Split PDF by Size' },
];
export default tools;
